sut:
  build: .
  dockerfile: Dockerfile.test
  links:
    - db
  environment:
    MARIADB_USER: user
    MARIADB_PASS: pass
    MARIADB_DATABASE: test_db
  entrypoint: /test.sh

db:
  build: .
  environment:
    MARIADB_USER: user
    MARIADB_PASS: pass
    MARIADB_DATABASE: test_db
  ports:
    - "3306:3306"
